### ISSUE TITLE
Blazing Infuser dont move items via pipes if output was occupied when a rod finished

### ISSUE THREAD

**Issue by NordicGamerFE** [McJtyMods/RFToolsPower#93]
As said in title the Blazing Infuser wont move items out of the input slot if the output slot was occupied when the item in the input slot finishes when the output slot is occupied even if the item in the output slot gets taken.
Modpack: Stoneblock 3 1.2.1

**Comment by McJty** [comment]
Sorry. I read that six times and still don't get it. What exactly is going on? What isn't working? Can you show some pictures perhaps?

**Comment by extremMiSt** [comment]
hi,

I think I have the same problem.

first things first:
I am in ftb stoneblock 3, with rftools power 1.18-4.0.7.

the problem is that if there is a rod getting to 100% while the output slot of the blazing infuser is full it ofc can't go there.
when I extract the rod in the output slot then the item in the input slot (that is already at 100%) does not go into the output slot, thus jamming the machine automation.

I have not found an ingame workaround yet, so a fix would be appreciated.

**Comment by extremMiSt** [comment]
oh I forgot to attach it, but here is a video of the aftermath
https://extremmist.de/files/2022_11_14-15:11:47.mp4

**Comment by extremMiSt** [comment]
I have had a look at the code, 

the problem is in src/main/java/mcjty/rftoolspower/modules/blazing/blocks/BlazingInfuserTileEntity.java
line 98 vs 107.
where items only try to get moved exactly when it reaches steps==0, but then no retries happen because 98 evals to false.

a solution would be to move the if of 107 to be an elseif (or a seperate if following it, if you insist on the rod being moved in the same tick it finishes) case of 98. thus always trying to move the item when it is done.

sadly I am not set up to compile and test mc mods or I'd make a pull request ... sorry for that.
but it seems easy enough to fix.

**Comment by McJty** [comment]
I will implement a fix tomorrow

**Comment by NordicGamerFE** [comment]
Thanks @McJty, Also gonna tag @Sunekaer so hes aware since we are playing stoneblock 3

**Comment by Sunekaer** [comment]
You really dont need to tag me

**Comment by NordicGamerFE** [comment]
> You really dont need to tag me

Got it chief :D

**Comment by McJty** [comment]
Fixed
